### Mean Squared Deviation (Scratch Code)

In [1]:
import pandas as pd

df = pd.DataFrame({'mileage':[19,19,20,20,20,21,21,21,
                              22,23,24,25,25,27,28,32,33,34,35]})
df

    mileage
0        19
1        19
2        20
3        20
4        20
5        21
6        21
7        21
8        22
9        23
10       24
11       25
12       25
13       27
14       28
15       32
16       33
17       34
18       35

In [4]:
# creating function
def mean_squared_deviation(a):
      
    # sum of all observation
    sum_of_observation = 0
    for i in a['mileage']:
        sum_of_observation += i
        
    # calculating mean where len(a['mileage']) means total number of observations   
    mean = sum_of_observation/len(a['mileage'])
    
    # calculating squared deviation
    squared_deviation = list()
    for i in a['mileage']:
        v = i-mean
        squared_deviation.append(v**2)
    
    # sum of all squared deviation
    sum_of_squared_deviation = 0
    for i in squared_deviation:
        sum_of_squared_deviation += i
    
    # total number of observations
    n = len(a)
    
    #formula for mean_squared_deviation
    msd = (1/n)*(sum_of_squared_deviation)
    return f'Mean Squared Deviation of mileage data is : {msd}'
        
        
        
mean_squared_deviation(df)

'Mean Squared Deviation of mileage data is : 27.058171745152357'